schema: schema.graphql
extensions:
  endpoints:
    Default GraphQL Endpoint:
      url: https://pdl-api.dev-fss-pub.nais.io/graphql
      headers:
        user-agent: pensjon-selvbetjening-opptjening-backend
      introspect: false