apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: pensjon-selvbetjening-opptjening-backend
  namespace: pensjonselvbetjening
  labels:
    team: pensjonselvbetjening
  annotations:
    nginx.ingress.kubernetes.io/proxy-buffer-size: "64k"
spec:
  image: {{ image }}
  ingresses:
    - https://pensjon-selvbetjening-opptjening-backend.intern.dev.nav.no
  port: 8080
  replicas:
    min: 2
    max: 2
  liveness:
    path: /internal/alive
    initialDelay: 30
    timeout: 1
    periodSeconds: 30
    failureThreshold: 5
  readiness:
    path: /internal/ready
  prometheus:
    enabled: true
    path: /internal/prometheus
  tokenx:
    enabled: true
  azure:
    application:
      enabled: true
      tenant: trygdeetaten.no
      claims:
        groups:
          - id: "9e122ddd-e542-4cc1-a7eb-92c99140fe0e" # 0000-GA-PENSJON_BRUKERHJELPA
          - id: "05ae245b-7b47-428a-9074-4ff6b59eddbc" # 0000-GA-Pensjon_Okonomi
          - id: "8bb9b8d1-f46a-4ade-8ee8-5895eccdf8cf" # 0000-GA-PENSJON_SAKSBEHANDLER
          - id: "a3f91493-1ab8-4b64-a544-0a77cbba9240" # 0000-GA-Pensjon_VEILEDER
          - id: "dbe4ad45-320b-4e9a-aaa1-73cca4ee124d" # 0000-GA-Egne_ansatte
          - id: "ea930b6b-9397-44d9-b9e6-f4cf527a632a" # 0000-GA-Fortrolig_Adresse
          - id: "5ef775f2-61f8-4283-bf3d-8d03f428aa14" # 0000-GA-Strengt_Fortrolig_Adresse
        extra:
          - NAVident
      replyURLs:
        - https://pensjon-veiledning-opptjening-frontend.intern.dev.nav.no/pensjon/opptjening/oauth2/internal/callback
        - https://pensjon-selvbetjening-opptjening-backend.intern.dev.nav.no/oauth2/internal/callback
        - http://localhost:3000/oauth2/internal/callback
        - http://localhost:8080/oauth2/internal/callback
  accessPolicy:
    inbound:
      rules:
        - application: pensjon-selvbetjening-opptjening-frontend
          cluster: dev-gcp
        - application: pensjon-veiledning-opptjening-frontend
          cluster: dev-gcp
        - application: azure-token-generator # dev only
          namespace: nais
        - application: tokenx-token-generator # dev only
          namespace: nais
    outbound:
      rules:
        - application: pdl-api
          namespace: pdl
          cluster: dev-fss
        - application: pensjon-pen-q2
          namespace: pensjon-q2
          cluster: dev-fss
        - application: pensjon-popp-q2
          namespace: pensjonopptjening
          cluster: dev-fss
        - application: pensjon-representasjon-q2
          namespace: pensjon-person
          cluster: dev-fss
        - application: skjermede-personer-pip
          namespace: nom
        - application: pensjon-pid-encryption
          namespace: pensjon-person
      external:
        - host: pdl-api.dev-fss-pub.nais.io
        - host: pensjon-pen-q2.dev-fss-pub.nais.io
        - host: pensjon-popp-q2.dev-fss-pub.nais.io
        - host: pensjon-representasjon-q2.dev-fss-pub.nais.io
        - host: skjermede-personer-pip.intern.dev.nav.no
        - host: test.idporten.no
  env:
    - name: NO_NAV_SECURITY_JWT_ISSUER_SELVBETJENING_COOKIE_NAME
      value: selvbetjening-idtoken
    - name: PENSJON_REPRESENTASJON_APP_ID
      value: dev-fss:pensjon-person:pensjon-representasjon-q2
    - name: PENSJON_REPRESENTASJON_URL
      value: https://pensjon-representasjon-q2.dev-fss-pub.nais.io
    - name: PDL_APP_ID
      value: dev-fss:pdl:pdl-api
    - name: PDL_URL
      value: https://pdl-api.dev-fss-pub.nais.io
    - name: PEN_URL
      value: https://pensjon-pen-q2.dev-fss-pub.nais.io
    - name: PEN_APP_ID
      value: dev-fss:pensjon-q2:pensjon-pen-q2
    - name: POPP_URL
      value: https://pensjon-popp-q2.dev-fss-pub.nais.io
    - name: SKJERMING_URL
      value: https://skjermede-personer-pip.intern.dev.nav.no
    - name: APP_ENVIRONMENT
      value: q2
    - name: COOKIES_DOMAIN
      value: nav.no
    - name: AZURE_APP_REDIRECT_URI
      value: https://pensjon-veiledning-opptjening-frontend.intern.dev.nav.no/pensjon/opptjening/oauth2/internal/callback
    - name: AUDIT_LOG_OUTPUT
      value: SYSLOG
    - name: STDOUT_LOG_OUTPUT
      value: JSON
    - name: PID_ENCRYPTION_URL
      value: http://pensjon-pid-encryption.pensjon-person
    - name: PID_ENCRYPTION_SCOPE
      value: api://dev-gcp.pensjon-person.pensjon-pid-encryption/.default
  envFrom:
    - configmap: loginservice-idporten
