apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: pensjon-selvbetjening-opptjening-backend
  namespace: pensjonselvbetjening
  labels:
    team: pensjonselvbetjening
  annotations:
    nginx.ingress.kubernetes.io/proxy-buffer-size: "128k"
spec:
  image: {{ image }}
  port: 8080
  replicas:
    min: 2
    max: 2
  liveness:
    path: "/api/internal/isAlive"
    initialDelay: 30
    timeout: 1
    periodSeconds: 30
    failureThreshold: 5
  ingresses:
    - https://pensjon-selvbetjening-opptjening-backend.nais.preprod.local
    - https://pensjon-selvbetjening-opptjening-backend.dev.intern.nav.no
    - https://pensjon-selvbetjening-opptjening-backend.dev-fss-pub.nais.io
  accessPolicy:
    inbound:
      rules:
        - application: pensjon-selvbetjening-opptjening-frontend
          cluster: dev-gcp
  readiness:
    path: "/api/internal/isReady"
  env:
    - name: NO_NAV_SECURITY_JWT_ISSUER_SELVBETJENING_COOKIE_NAME
      value: selvbetjening-idtoken
    - name: HTTP_PROXY_PARAMETERNAME
      value: "http.proxy"
    - name: PDL_URL
      value: https://pdl-api.dev-fss.nais.io
    - name: PEN_URL
      value: https://pensjon-pen-q2.dev.adeo.no
    - name: POPP_URL
      value: https://pensjon-popp-q2.dev.adeo.no
    - name: SKJERMING_URL
      value: https://skjermede-personer-pip.dev.adeo.no
    - name: STS_URL
      value: https://security-token-service.dev.adeo.no
    - name: UNLEASH_URL
      value: https://unleash.nais.io
    - name: APP_ENVIRONMENT
      value: q2
    - name: AZURE_APP_REDIRECT_URI
      value: https://pensjon-selvbetjening-opptjening-frontend.dev.adeo.no/pensjon/opptjening/oauth2/internal/callback
    - name: AUDIT_LOG_OUTPUT
      value: SYSLOG
    - name: STDOUT_LOG_OUTPUT
      value: CONSOLE
  envFrom:
    - configmap: loginservice-idporten
  azure:
    application:
      enabled: true
      tenant: nav.no
      claims:
        groups:
          - id: "7845a796-1516-4d14-b500-fd65c001f35c" # 0000-GA-PENSJON_BRUKERHJELPA
          - id: "70ef8e7f-7456-4298-95e0-b13c0ef2422b" # 0000-GA-Pensjon_Okonomi
          - id: "0af3955f-df85-4eb0-b5b2-45bf2c8aeb9e" # 0000-GA-PENSJON_SAKSBEHANDLER
          - id: "959ead5b-99b5-466b-a0ff-5fdbc687517b" # 0000-GA-Pensjon_VEILEDER
          - id: "676b5e1f-84e6-46e5-8814-04233699ed4b" # 0000-GA-Pensjon_UTVIDET
          - id: "c10e6466-4d28-4467-8e93-43cacfbcff92" # DEV ONLY: 0000-GA-UTVIKLING-FRA-LAPTOP
        extra:
          - NAVident
      replyURLs:
        - https://pensjon-selvbetjening-opptjening-frontend.dev.adeo.no/pensjon/opptjening/oauth2/internal/callback
        - http://localhost:8080/oauth2/internal/callback
        - http://localhost:3000/oauth2/internal/callback
  webproxy: true
  prometheus:
    enabled: true
    path: /api/mgmt/prom
  vault:
    enabled: true
    paths:
      # Managed secrets
      - kvPath: /serviceuser/data/dev/srvpensjon
        mountPath: /secrets/serviceuser

