apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: pensjon-selvbetjening-opptjening-backend
  namespace: pensjonselvbetjening
  labels:
    team: pensjonselvbetjening
  annotations:
    nginx.ingress.kubernetes.io/proxy-buffer-size: "128k"
spec:
  image: {{ image }}
  ingresses:
    - https://pensjon-selvbetjening-opptjening-backend.intern.nav.no
  port: 8080
  replicas:
    min: 2
    max: 4
  liveness:
    path: /internal/alive
    initialDelay: 30
    timeout: 1
    periodSeconds: 30
    failureThreshold: 5
  readiness:
    path: /internal/ready
    initialDelay: 3
    timeout: 1
  prometheus:
    enabled: true
    path: /internal/prometheus
  tokenx:
    enabled: true
  azure:
    application:
      enabled: true
      tenant: nav.no
      claims:
        groups:
          - id: "7845a796-1516-4d14-b500-fd65c001f35c" # 0000-GA-PENSJON_BRUKERHJELPA
          - id: "70ef8e7f-7456-4298-95e0-b13c0ef2422b" # 0000-GA-Pensjon_Okonomi
          - id: "0af3955f-df85-4eb0-b5b2-45bf2c8aeb9e" # 0000-GA-PENSJON_SAKSBEHANDLER
          - id: "959ead5b-99b5-466b-a0ff-5fdbc687517b" # 0000-GA-Pensjon_VEILEDER
          - id: "e750ceb5-b70b-4d94-b4fa-9d22467b786b" # 0000-GA-Egne_ansatte
          - id: "9ec6487d-f37a-4aad-a027-cd221c1ac32b" # 0000-GA-Fortrolig_Adresse
          - id: "ad7b87a6-9180-467c-affc-20a566b0fec0" # 0000-GA-Strengt_Fortrolig_Adresse
        extra:
          - NAVident
      replyURLs:
        - https://pensjon-veiledning-opptjening-frontend.intern.nav.no/pensjon/opptjening/oauth2/internal/callback
  accessPolicy:
    inbound:
      rules:
        - application: pensjon-selvbetjening-opptjening-frontend
          cluster: prod-gcp
        - application: pensjon-veiledning-opptjening-frontend
          cluster: prod-gcp
    outbound:
      rules:
        - application: pdl-api
          namespace: pdl
          cluster: prod-fss
        - application: pensjon-pen
          namespace: pensjondeployer
          cluster: prod-fss
        - application: pensjon-popp
          namespace: pensjonopptjening
          cluster: prod-fss
        - application: pensjon-representasjon
          namespace: pensjon-person
          cluster: prod-fss
        - application: skjermede-personer-pip
          namespace: nom
        - application: pensjon-pid-encryption
          namespace: pensjon-person
      external:
        - host: pdl-api.prod-fss-pub.nais.io
        - host: pensjon-pen.prod-fss-pub.nais.io
        - host: pensjon-popp.prod-fss-pub.nais.io
        - host: pensjon-representasjon.prod-fss-pub.nais.io
        - host: skjermede-personer-pip.intern.nav.no
        - host: idporten.no
        - host: oidc.difi.no
  env:
    - name: NO_NAV_SECURITY_JWT_ISSUER_SELVBETJENING_COOKIE_NAME
      value: selvbetjening-idtoken
    - name: PENSJON_REPRESENTASJON_APP_ID
      value: prod-fss:pensjon-person:pensjon-representasjon
    - name: PENSJON_REPRESENTASJON_URL
      value: https://pensjon-representasjon.prod-fss-pub.nais.io
    - name: PDL_APP_ID
      value: prod-fss:pdl:pdl-api
    - name: PDL_URL
      value: https://pdl-api.prod-fss-pub.nais.io
    - name: PEN_URL
      value: https://pensjon-pen.prod-fss-pub.nais.io
    - name: PEN_APP_ID
      value: prod-fss:pensjondeployer:pensjon-pen
    - name: PENSJONSOPPTJENING_REGISTER_APP_ID
      value: prod-fss:pensjonopptjening:pensjon-popp
    - name: POPP_URL
      value: https://pensjon-popp.prod-fss-pub.nais.io
    - name: SKJERMEDE_PERSONER_PIP_APP_ID
      value: prod-gcp:nom:skjermede-personer-pip
    - name: SKJERMING_URL
      value: https://skjermede-personer-pip.intern.nav.no
    - name: FRONTEND_CLIENT_ID
      value: 35e23674-b465-4664-88c6-ae7539d67f5d
    - name: IDPORTEN_ISSUER
      value: https://idporten.no
    - name: BRUKERHJELP_GROUP_ID
      value: 7845a796-1516-4d14-b500-fd65c001f35c
    - name: OEKONOMI_GROUP_ID
      value: 70ef8e7f-7456-4298-95e0-b13c0ef2422b
    - name: SAKSBEHANDLER_GROUP_ID
      value: 0af3955f-df85-4eb0-b5b2-45bf2c8aeb9e
    - name: VEILEDER_GROUP_ID
      value: 959ead5b-99b5-466b-a0ff-5fdbc687517b
    - name: EGNE_ANSATTE_TILGANG_GROUP_ID
      value: e750ceb5-b70b-4d94-b4fa-9d22467b786b
    - name: FORTROLIG_ADRESSE_TILGANG_GROUP_ID
      value: 9ec6487d-f37a-4aad-a027-cd221c1ac32b
    - name: STRENGT_FORTROLIG_ADRESSE_TILGANG_GROUP_ID
      value: ad7b87a6-9180-467c-affc-20a566b0fec0
    - name: APP_ENVIRONMENT
      value: p
    - name: COOKIES_DOMAIN
      value: nav.no
    - name: AZURE_APP_REDIRECT_URI
      value: https://pensjon-veiledning-opptjening-frontend.intern.nav.no/pensjon/opptjening/oauth2/internal/callback
    - name: AUDIT_LOG_OUTPUT
      value: SYSLOG
    - name: STDOUT_LOG_OUTPUT
      value: JSON
    - name: PID_ENCRYPTION_URL
      value: http://pensjon-pid-encryption.pensjon-person
    - name: PID_ENCRYPTION_SCOPE
      value: api://prod-gcp.pensjon-person.pensjon-pid-encryption/.default
  envFrom:
    - configmap: loginservice-idporten
