apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: pensjon-selvbetjening-opptjening-backend
  namespace: pensjonselvbetjening
  labels:
    team: pensjonselvbetjening
spec:
  image: {{ image }}
  port: 8080
  replicas:
    min: 2
    max: 2
  liveness:
    path: "/api/internal/isAlive"
    initialDelay: 30
    timeout: 1
    periodSeconds: 30
    failureThreshold: 5
  ingresses:
    - https://pensjon-selvbetjening-opptjening-backend.adeo.no
    - https://pensjon-selvbetjening-opptjening-backend.nais.adeo.no
  readiness:
    path: "/api/internal/isReady"
    initialDelay: 3
    timeout: 1
  env:
    - name: NO_NAV_SECURITY_JWT_ISSUER_SELVBETJENING_COOKIE_NAME
      value: selvbetjening-idtoken
    - name: HTTP_PROXY_PARAMETERNAME
      value: "http.proxy"
    - name: STS_ENDPOINT_URL
      value: https://security-token-service.nais.adeo.no/rest/v1/sts/token
    - name: PEN_ENDPOINT_URL
      value: https://pensjon-pen.nais.adeo.no/pen/api/
    - name: POPP_ENDPOINT_URL
      value: https://pensjon-popp.nais.adeo.no/popp/api
    - name: PDL_ENDPOINT_URL
      value: https://pdl-api.nais.adeo.no/graphql
    - name: SKJERMING_ENDPOINT_URL
      value: https://skjermede-personer-pip.nais.adeo.no/
    - name: UNLEASH_ENDPOINT_URL
      value: https://unleash.nais.io/api
    - name: APP_ENVIRONMENT
      value: p
    - name: AZURE_APP_REDIRECT_URI
      value: https://pensjon-selvbetjening-opptjening-frontend.intern.nav.no/pensjon/opptjening/oauth2/internal/callback
    - name: AUDIT_LOG_OUTPUT
      value: SYSLOG
    - name: STDOUT_LOG_OUTPUT
      value: JSON
  envFrom:
    - configmap: loginservice-idporten
  azure:
    application:
      enabled: true
      tenant: nav.no
      claims:
        groups:
          - id: "7845a796-1516-4d14-b500-fd65c001f35c" # 0000-GA-PENSJON_BRUKERHJELPA
          - id: "70ef8e7f-7456-4298-95e0-b13c0ef2422b" # 0000-GA-Pensjon_Okonomi
          - id: "0af3955f-df85-4eb0-b5b2-45bf2c8aeb9e" # 0000-GA-PENSJON_SAKSBEHANDLER
          - id: "959ead5b-99b5-466b-a0ff-5fdbc687517b" # 0000-GA-Pensjon_VEILEDER
          - id: "676b5e1f-84e6-46e5-8814-04233699ed4b" # 0000-GA-Pensjon_UTVIDET
        extra:
          - NAVident
      replyURLs:
        - https://pensjon-selvbetjening-opptjening-frontend.intern.nav.no/pensjon/opptjening/oauth2/internal/callback
  webproxy: true
  prometheus:
    enabled: true
    path: /api/mgmt/prom
  vault:
    enabled: true
    paths:
      - kvPath: /serviceuser/data/prod/srvpensjon
        mountPath: /secrets/serviceuser
