package no.nav.pensjon.selvbetjeningopptjening.security.dto;

// Generated by www.jsonschema2pojo.org

import java.util.HashMap;
import java.util.List;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

@SuppressWarnings("unused")
@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonPropertyOrder({
        "aud",
        "iss",
        "iat",
        "nbf",
        "exp",
        "acct",
        "acr",
        "aio",
        "amr",
        "app_displayname",
        "appid",
        "appidacr",
        "deviceid",
        "family_name",
        "given_name",
        "ipaddr",
        "name",
        "oid",
        "onprem_sid",
        "platf",
        "puid",
        "rh",
        "scp",
        "signin_state",
        "sub",
        "tenant_region_scope",
        "tid",
        "unique_name",
        "upn",
        "uti",
        "ver",
        "xms_st",
        "xms_tcdt"
})
public class AccessTokenDto {

    @JsonProperty("aud")
    private String aud;
    @JsonProperty("iss")
    private String iss;
    @JsonProperty("iat")
    private Integer iat;
    @JsonProperty("nbf")
    private Integer nbf;
    @JsonProperty("exp")
    private Integer exp;
    @JsonProperty("acct")
    private Integer acct;
    @JsonProperty("acr")
    private String acr;
    @JsonProperty("aio")
    private String aio;
    @JsonProperty("amr")
    private List<String> amr = null;
    @JsonProperty("app_displayname")
    private String appDisplayname;
    @JsonProperty("appid")
    private String appid;
    @JsonProperty("appidacr")
    private String appidacr;
    @JsonProperty("deviceid")
    private String deviceid;
    @JsonProperty("family_name")
    private String familyName;
    @JsonProperty("given_name")
    private String givenName;
    @JsonProperty("ipaddr")
    private String ipaddr;
    @JsonProperty("name")
    private String name;
    @JsonProperty("oid")
    private String oid;
    @JsonProperty("onprem_sid")
    private String onpremSid;
    @JsonProperty("platf")
    private String platf;
    @JsonProperty("puid")
    private String puid;
    @JsonProperty("rh")
    private String rh;
    @JsonProperty("scp")
    private String scp;
    @JsonProperty("signin_state")
    private List<String> signinState = null;
    @JsonProperty("sub")
    private String sub;
    @JsonProperty("tenant_region_scope")
    private String tenantRegionScope;
    @JsonProperty("tid")
    private String tid;
    @JsonProperty("unique_name")
    private String uniqueName;
    @JsonProperty("upn")
    private String upn;
    @JsonProperty("uti")
    private String uti;
    @JsonProperty("ver")
    private String ver;
    @JsonProperty("xms_st")
    private XmsStDto xmsSt;
    @JsonProperty("xms_tcdt")
    private Integer xmsTcdt;
    @JsonIgnore
    private Map<String, Object> additionalProperties = new HashMap<>();

    @JsonProperty("aud")
    public String getAud() {
        return aud;
    }

    @JsonProperty("aud")
    public void setAud(String aud) {
        this.aud = aud;
    }

    @JsonProperty("iss")
    public String getIss() {
        return iss;
    }

    @JsonProperty("iss")
    public void setIss(String iss) {
        this.iss = iss;
    }

    @JsonProperty("iat")
    public Integer getIat() {
        return iat;
    }

    @JsonProperty("iat")
    public void setIat(Integer iat) {
        this.iat = iat;
    }

    @JsonProperty("nbf")
    public Integer getNbf() {
        return nbf;
    }

    @JsonProperty("nbf")
    public void setNbf(Integer nbf) {
        this.nbf = nbf;
    }

    @JsonProperty("exp")
    public Integer getExp() {
        return exp;
    }

    @JsonProperty("exp")
    public void setExp(Integer exp) {
        this.exp = exp;
    }

    @JsonProperty("acct")
    public Integer getAcct() {
        return acct;
    }

    @JsonProperty("acct")
    public void setAcct(Integer acct) {
        this.acct = acct;
    }

    @JsonProperty("acr")
    public String getAcr() {
        return acr;
    }

    @JsonProperty("acr")
    public void setAcr(String acr) {
        this.acr = acr;
    }

    @JsonProperty("aio")
    public String getAio() {
        return aio;
    }

    @JsonProperty("aio")
    public void setAio(String aio) {
        this.aio = aio;
    }

    @JsonProperty("amr")
    public List<String> getAmr() {
        return amr;
    }

    @JsonProperty("amr")
    public void setAmr(List<String> amr) {
        this.amr = amr;
    }

    @JsonProperty("app_displayname")
    public String getAppDisplayname() {
        return appDisplayname;
    }

    @JsonProperty("app_displayname")
    public void setAppDisplayname(String appDisplayname) {
        this.appDisplayname = appDisplayname;
    }

    @JsonProperty("appid")
    public String getAppid() {
        return appid;
    }

    @JsonProperty("appid")
    public void setAppid(String appid) {
        this.appid = appid;
    }

    @JsonProperty("appidacr")
    public String getAppidacr() {
        return appidacr;
    }

    @JsonProperty("appidacr")
    public void setAppidacr(String appidacr) {
        this.appidacr = appidacr;
    }

    @JsonProperty("deviceid")
    public String getDeviceid() {
        return deviceid;
    }

    @JsonProperty("deviceid")
    public void setDeviceid(String deviceid) {
        this.deviceid = deviceid;
    }

    @JsonProperty("family_name")
    public String getFamilyName() {
        return familyName;
    }

    @JsonProperty("family_name")
    public void setFamilyName(String familyName) {
        this.familyName = familyName;
    }

    @JsonProperty("given_name")
    public String getGivenName() {
        return givenName;
    }

    @JsonProperty("given_name")
    public void setGivenName(String givenName) {
        this.givenName = givenName;
    }

    @JsonProperty("ipaddr")
    public String getIpaddr() {
        return ipaddr;
    }

    @JsonProperty("ipaddr")
    public void setIpaddr(String ipaddr) {
        this.ipaddr = ipaddr;
    }

    @JsonProperty("name")
    public String getName() {
        return name;
    }

    @JsonProperty("name")
    public void setName(String name) {
        this.name = name;
    }

    @JsonProperty("oid")
    public String getOid() {
        return oid;
    }

    @JsonProperty("oid")
    public void setOid(String oid) {
        this.oid = oid;
    }

    @JsonProperty("onprem_sid")
    public String getOnpremSid() {
        return onpremSid;
    }

    @JsonProperty("onprem_sid")
    public void setOnpremSid(String onpremSid) {
        this.onpremSid = onpremSid;
    }

    @JsonProperty("platf")
    public String getPlatf() {
        return platf;
    }

    @JsonProperty("platf")
    public void setPlatf(String platf) {
        this.platf = platf;
    }

    @JsonProperty("puid")
    public String getPuid() {
        return puid;
    }

    @JsonProperty("puid")
    public void setPuid(String puid) {
        this.puid = puid;
    }

    @JsonProperty("rh")
    public String getRh() {
        return rh;
    }

    @JsonProperty("rh")
    public void setRh(String rh) {
        this.rh = rh;
    }

    @JsonProperty("scp")
    public String getScp() {
        return scp;
    }

    @JsonProperty("scp")
    public void setScp(String scp) {
        this.scp = scp;
    }

    @JsonProperty("signin_state")
    public List<String> getSigninState() {
        return signinState;
    }

    @JsonProperty("signin_state")
    public void setSigninState(List<String> signinState) {
        this.signinState = signinState;
    }

    @JsonProperty("sub")
    public String getSub() {
        return sub;
    }

    @JsonProperty("sub")
    public void setSub(String sub) {
        this.sub = sub;
    }

    @JsonProperty("tenant_region_scope")
    public String getTenantRegionScope() {
        return tenantRegionScope;
    }

    @JsonProperty("tenant_region_scope")
    public void setTenantRegionScope(String tenantRegionScope) {
        this.tenantRegionScope = tenantRegionScope;
    }

    @JsonProperty("tid")
    public String getTid() {
        return tid;
    }

    @JsonProperty("tid")
    public void setTid(String tid) {
        this.tid = tid;
    }

    @JsonProperty("unique_name")
    public String getUniqueName() {
        return uniqueName;
    }

    @JsonProperty("unique_name")
    public void setUniqueName(String uniqueName) {
        this.uniqueName = uniqueName;
    }

    @JsonProperty("upn")
    public String getUpn() {
        return upn;
    }

    @JsonProperty("upn")
    public void setUpn(String upn) {
        this.upn = upn;
    }

    @JsonProperty("uti")
    public String getUti() {
        return uti;
    }

    @JsonProperty("uti")
    public void setUti(String uti) {
        this.uti = uti;
    }

    @JsonProperty("ver")
    public String getVer() {
        return ver;
    }

    @JsonProperty("ver")
    public void setVer(String ver) {
        this.ver = ver;
    }

    @JsonProperty("xms_st")
    public XmsStDto getXmsSt() {
        return xmsSt;
    }

    @JsonProperty("xms_st")
    public void setXmsSt(XmsStDto xmsSt) {
        this.xmsSt = xmsSt;
    }

    @JsonProperty("xms_tcdt")
    public Integer getXmsTcdt() {
        return xmsTcdt;
    }

    @JsonProperty("xms_tcdt")
    public void setXmsTcdt(Integer xmsTcdt) {
        this.xmsTcdt = xmsTcdt;
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    @JsonAnySetter
    public void setAdditionalProperty(String name, Object value) {
        this.additionalProperties.put(name, value);
    }
}
