package no.nav.pensjon.selvbetjeningopptjening.security.dto;

// Generated by www.jsonschema2pojo.org

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

@SuppressWarnings({"unused"})
@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonPropertyOrder({
        "keys"
})
public class JwtKeysDto {

    @JsonProperty("keys")
    private List<JwtKeyDto> keys = null;
    @JsonIgnore
    private Map<String, Object> additionalProperties = new HashMap<>();

    @JsonProperty("keys")
    public List<JwtKeyDto> getKeys() {
        return keys;
    }

    @JsonProperty("keys")
    public void setKeys(List<JwtKeyDto> keys) {
        this.keys = keys;
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    @JsonAnySetter
    public void setAdditionalProperty(String name, Object value) {
        this.additionalProperties.put(name, value);
    }
}
