== Avhengigheter
Applikasjonen har eksterne avhengigheter til POPP (registeret for pensjonsopptjening) og PEN (den pensjonsfaglige kjerne).
Det er fra disse to stedene applikajsonen får rådataene den trenger for å utføre sin nødvendige forretningslogikk.
I mange av tilfellene har ikke applikasjonen behov for alle dataene den får fra de eksterne tjenestene, kun en liten del av dataene,
men siden de eksterne tjenestene er generaliserte mottas disse dataene likevel.

Pensjon-selvbetjening-opptjening-backend har følgende eksterne avhengigheter:

=== Avhengigheter til POPP

==== [#propopp006]#PROPOPP006 HentPensjonsbeholdningListe#
.Bruk av data fra PROPOPP006
PROPOPP006 leverer en liste med beholdning-objekter som beskriver en brukers pensjonsbeholdning. Hvert beholdning-objekt
representerer pensjonsbehlodning-data for en bestemt periode definert med en fom-dato og en tom-dato. Disse dataene
er veldig sentrale applikasjonens forretningslogikk for å kunne vise hvordan pensjonsbeholdningen har utviklet seg
for brukere født etter 1953.

.Domene-objekter relevante for PROPOPP006:
[options="header,footer"]
|=======================
|Objekt|Beskrivelse
|[#beholdning]#Beholdning#|Selve beholdning-objektet som tjenesten returnerer en liste bestående av.
|Lonnsvekstregulering|Et objekt som ligger på Beholdning-objektet og som beskriver hvor mye beholdningen har endret seg som følge av regulering.
|InntektOpptjeningBelop|Et objekt som ligger på Beholdning-objektet og som beskriver hvor mye beholdningen har blitt endret som følge av ny opptjening.
|OmsorgOpptjeningBelop|Et objekt som ligger på Beholdning-objektet og som beskriver hvor mye beholdningen har endret seg som følge av omsorgsopptjening.
|DagpengerOpptjeningBelop|Et objekt som ligger på Beholdning-objektet og som beskriver hvor mye beholdningen har endret seg som følge av dagpenger.
|ForstegangstjenesteOpptjeningBelop|Et objekt som ligger på Beholdning-objektet og som beskriver hvor mye beholdningen har endret seg som følge av førstegangstjeneste.
|UforeOpptjeningBelop|Et objekt som ligger på Beholdning-objektet og som beskriver hvor mye beholdningen har endret seg som følge av uføre.
|Inntekt|Et objekt som ligger på InntektOpptjeningBelop-objektet som beskriver en inntekt for personen for et gitt år.
|Omsorg|Et objekt som ligger på OmsorgOpptjeningBelop-objektet som beskriver hvilken omsorgstype en person med omsorgsopptjening har hatt.
|Dagpenger|Et objekt som ligger på DagpengerOpptjeningBelop som inneholder informasjon om dagpenger en person har hatt for et bestemt år.
|Forstegangstjeneste|Et objekt som ligger på ForstegangstjenesteOpptjeningBelop-objektet og som innheholder førstegangstjenesteperioder for en person.
|FørstegangstjenestePeriode|Et objekt som ligger på Forstegangstjeneste-objektet og beskriver en periode med førstegangstjeneste.
|=======================
Disse domeneobjektene tilhører POPP, se POPP-dokumentasjon for ytterligere detaljer.


==== [#propopp007]#PROPOPP007 HentOpptjeningsgrunnlag#
.Bruk av data fra PROPOPP007
PROPOPP007 returnerer en liste av inntekt-objekter. Hvert inntekt-objekt representerer en inntekt personen hadde på et gitt år.
Dataene fra PROPOPP007 brukes kun for å hente inntekter for personer som tilhører brukergruppe <<index.adoc#userGroup,USER_GROUP_5>>.
For brukergruppe <<index.adoc#userGroup,USER_GROUP_4>> hentes inntekt direkte fra beholdning-objektet man fikk fra <<index.adoc#propopp006,PROPOPP0006>>, mens for øvrige
brukergrupper hentes inntekten fra pensjonspoeng-objektet man fikk fra <<index.adoc#propopp019,PROPOPP019>>.

.Domene-objekter relevante for PROPOPP007:
[options="header,footer"]
|=======================
|Objekt|Beskrivelse
|Inntekt|Et objekt som beskriver inntekten en bruker hadde for et bestemt år.
|=======================
Disse domeneobjektene tilhører POPP, se POPP-dokumentasjon for ytterligere detaljer.

==== [#propopp019]#PROPOPP019 HentPensjonspoengListe#
.Bruk av data fra PROPOPP019
PROPOPP019 returnerer en liste med pensjonspoeng-objekter. Et slikt pensjonspoeng-objekt beskriver
pensjonspoengene for et gitt år for en person. Pensjonspoengene er relevante for å vise opptjeningsinformasjon for
brukere født i perioden før 1963, altså alle <<index.adoc#userGroup,brukergrupper>> bortsett fra <<index.adoc#userGroup,USER_GROUP_5>>.
For brukere i <<index.adoc#userGroup,USER_GROUP_1, USER_GROUP_2 eller USER_GROUP_3>> hentes i tillegg også inntektsinformasjon fra
pensjonspoeng-objektene.

.Domene-objekter relevante for PROPOPP019:
[options="header,footer"]
|=======================
|Objekt|Beskrivelse
|Pensjonspoeng|Et objekt som beskriver informasjon om pensjonspoeng for en bruker for et gitt år.
|Inntekt|Et objekt som ligger på Pensjonspoeng-objektet og beskriver inntekten en bruker hadde for et bestemt år.
|=======================
Disse domeneobjektene tilhører POPP, se POPP-dokumentasjon for ytterligere detaljer.

==== [#propopp013]#PROPOPP013 HentRestpensjoner#
.Bruk av data fra PROPOPP013
PROPOPP013 returnerer en liste med restpensjon-objekter. Et slikt restpensjon-objekt bekskriver restpensjonen for en bruker
for et gitt år. Restpensjonsdataene er aktuelle å bruke og vise i applikasjonens respons i tilfeller hvor bruker har gradert
alderspensjon. Detter er aktuelt for alle brukergrupper bortsett fra <<index.adoc#userGroup,USER_GROUP_1>>.

.Domene-objekter relevante for PROPOPP013:
[options="header,footer"]
|=======================
|Objekt|Beskrivelse
|Restpensjon|Inneholder data angående restpensjonen for en bruker for et gitt år.
|Pensjonspoeng|Restpensjon-objektet har en liste med pensjonspoeng-objekter.
|=======================
Disse domeneobjektene tilhører POPP, se POPP-dokumentasjon for ytterligere detaljer.

=== Avhengigheter til PEN

==== [#propen2602]#PROPEN2602 GetAfphistorikkForPerson#
.Bruk av data fra PROPEN2602
Tjenesten PROPEN2602 ble opprettet i PEN for å dekke behovet pensjon-selvbetjening-opptjening-backend har for å
kunne hente AFP-historikk via REST. Tjenesten returnerer AFP-historikk for en person som brukes for å avgjøre om en person
har AFP på et gitt år, og dermed legge ved en merknad i responsen om dette.

.Domene-objekter relevante for PROPEN2602:
[options="header,footer"]
|=======================
|Objekt|Beskrivelse
|AfpHistorikk|Et objekt som inneholder virkFom og virkTom for brukerens AFP.
|=======================
Disse domeneobjektene tilhører PEN, se PEN-dokumentasjon for ytterligere detaljer.

==== [#propen2603]#PROPEN2603 GetUforehistorikkForPerson#
.Bruk av data fra PROPEN2603
Tjenesten PROPEN2603 ble opprettet i PEN for å dekke behovet pensjon-selvbetjening-opptjening-backend har for å
kunne hente uførehistorikk via REST. Tjenesten returnerer uførehistorikk for en person som brukes for å avgjøre om en person
har uføretrygd på et gitt år, og dermed legge ved en merknad i responsen om dette.

.Domene-objekter relevante for PROPEN2602:
[options="header,footer"]
|=======================
|Objekt|Beskrivelse
|UforeHistorikk|Et objekt som inneholder uføreperioder for en person.
|UforePeriode|Et objekt som ligger i UforeHistorikk og beskriver fom, tom, type og uføregrad en bruker hadde i en periode.
|=======================
Disse domeneobjektene tilhører PEN, se PEN-dokumentasjon for ytterligere detaljer.

==== [#propen3000]#PROPEN3000 GetUttaksgradForVedtak#
.Bruk av data fra PROPEN3000
Tjenesten PROPEN3000 ble opprettet i PEN for å dekke behovet pensjon-selvbetjening-opptjening-backend har for å
kunne hente uttaksgrad for alderspensjon via REST. Basert på vedtakId man gir som input til tjenesten, returnerer
den en liste med uttaksgrad-objekter som beskriver uttaksgrad en person hadde knyttet til det aktuelle vedtaket.
Tjenesten benyttes for å identifisere når bruker har uttak av alderspensjon, og hvor stort dette uttaket er.

.Domene-objekter relevante for PROPEN3000:
[options="header,footer"]
|=======================
|Objekt|Beskrivelse
|Uttaksgrad|Beskriver fom, tom, grad og tilknyttet vedtak for en uttaksgrad en person har hatt.
|=======================
Disse domeneobjektene tilhører PEN, se PEN-dokumentasjon for ytterligere detaljer.

==== [#propen3001]#PROPEN3001 GetAlderSakUttaksgradhistorikkForPerson#
.Bruk av data fra PROPEN3001
Tjenesten PROPEN3001 ble opprettet i PEN for å dekke behovet pensjon-selvbetjening-opptjening-backend har for å
kunne hente uttaksgrad for alderspensjon via REST. Basert på fnr som gis inn som input returneres alle uttaksgrader
som er registrert på den aktuelle personen. Tjenesten benyttes for å identifisere når bruker har uttak av alderspensjon,
og hvor stort dette uttaket er.

.Domene-objekter relevante for PROPEN3000:
[options="header,footer"]
|=======================
|Objekt|Beskrivelse
|Uttaksgrad|Beskriver fom, tom og grad for en uttaksgrad en person har hatt. Feltet vedtakId er tomt.
|=======================
Disse domeneobjektene tilhører PEN, se PEN-dokumentasjon for ytterligere detaljer.

=== Avhengigheter til PDL
PDL (persondataløsningen) er NAVs interne register for grunnleggende personopplysninger. Registeret inneholder
opplysninger om alle personer i Folkeregisteret og andre kilder til persondata som Nav har tilgang til.

.Bruk av data fra PDL
Applikasjonen trenger å identifisere en brukers fødselsdato for å plassere brukeren i riktig <<index.adoc#userGroup,brukergruppe>>.
For å få mest mulig korrekt fødselsdato, hentes dette derfor fra PDL. Men i de aller fleste tilfeller kan egentlig
fødselsdato utledes fra selve fødselsnummeret. Derfor vil applikasjonen i tilfeller hvor kallet til PDL feiler alltid prøve å utlede
fødselsåret i stedet basert på den informasjonen det har. Det første som kan skje er at PDL ikke returnerer en fødselsdato, men
kun fødselsåret. Da setter applikasjonen fødselsdatoen til første dag i fødselsåret. Dette er en løsning som vil fungere
fordi man først og fremst er interessert i fødselsåret for å plassere brukerne i brukergruppene. Skulle kallet til PDL
feile fullstendig vil applikasjonen prøve å utlede fødselsdato fra selve fødselsnummeret som en siste backup. Hvis
dette også feiler har applikasjonen ikke noe annet valg enn å returnere feilmelding til frontend, fordi ingenting kan
gjøres uten å vite når brukeren er født.

I tillegg til fødselsdato hentes også brukers navn fra PDL. Navnet brukes kun i visning til bruker. Det hentes fornavn,
mellomnavn og etternavn. En bruker kan ha registrert flere navn. Ett navn i folkeregisteret og ett navn som er registrert
hos NAV. I valg av navn velges den av disse som det sist ble gjort endring på. For å finne ut når et navn ble endret
sist brukes ajourholdstidspunkt for navn fra Folkeregisteret. Ajourholdstidspunkt hentes fra folkeregistermaetadata
som returneres av PDL. For NAV-navn brukes listen endringer i metadata for å avgjøre når navnet sist ble endret.

.Strategi for henting av data
Data fra PDL hentes ved å spesifisere en GraphQL-spørring som beskriver hvilke data som man vil ha. PDL inneholder
ganske mange forskjellige data om en person. Man ønsker ikke å hente mer data om en person enn det man trenger for å
utføre den tjenesten man skal gi brukeren. Gitt at man her kun trenger fødselsdato og fødselsår, vil man kun trenge
å benytte operasjonen hentPerson, hvor man spesifiserer at man vil hente opplysningstypen fødsel med
informasjonselementene fødselsdato og fødselsår. Det er også et mål at man ikke ønsker å ha mange gjentatte kall til PDL.
Derfor kaller applikasjonen PDL kun en gang, og så spesifiserer man alt som applikasjonen kommer til å få bruk for
i dette kallet, i stedet for å spørre en gang til senere hvis man plutselig trenger mer data.

.Eksempel på respons fra PDL
[source,perl]
----
{
    "data": {
        "hentPerson": {
            "navn": [
                {
                    "fornavn": "KLØKTIG",
                    "mellomnavn": null,
                    "etternavn": "POTET",
                    "folkeregistermetadata": {
                        "ajourholdstidspunkt": "2021-03-26T10:56:01"
                    },
                    "metadata": {
                        "master": "FREG",
                        "endringer": [
                            {
                                "registrert": "2021-03-26T10:56:01"
                            }
                        ]
                    }
                }
            ],
            "foedsel": [
                {
                    "foedselsdato": "1972-11-05",
                    "foedselsaar": null
                }
            ]
        }
    }
}
----
Merk at en person kan ha flere fødselsdatoer registrert på seg. Applikasjonen velger da den første i lista.


