== Beskrivelse
.Hensikt
Applikasjonen pensjon-selvbetjening-opptjening-backend er en applikasjon som samler
inn rådata fra primært POPP (register for pensjonsopptjening) og PEN (pensjonsfaglig kjerne)
og orkestrerer disse dataene slik at de kan hentes og presenteres til bruker av applikasjonen
pensjon-selvbetjening-opptjening-frontend.

.Hvordan ta i bruk applikasjonen
Applikasjonen eksponeres som REST-endepunkt og har følgende API:

[options="header,footer"]
|=======================
|Type   |Path                |Beskrivelse                                                                       |Merknad
|GET    |/api/opptjening     |Returnerer alle de ferdig orkestrerte dataene for opptjening for en gitt person.  |Her trengs brukers personnummer som input, dette henter applikasjonen fra et oidc-token som må være satt som cookie.

|=======================

.Eksempel på respons fra /api/opptjening
[source,perl]
----
{
    "opptjeningData": {
        "2017": {
                    "pensjonsgivendeInntekt": 454097,
                    "pensjonsbeholdning": 3082627,
                    "omsorgspoeng": null,
                    "omsorgspoengType": null,
                    "pensjonspoeng": 3.87,
                    "merknader": [],
                    "restpensjon": null,
                    "maksUforegrad": 0,
                    "endringOpptjening": [
                        {
                            "dato": "2016-12-31",
                            "arsakType": "INNGAENDE",
                            "arsakDetails": null,
                            "endringBelop": null,
                            "pensjonsbeholdningBelop": 2964191.409863046,
                            "uttaksgrad": 0
                        },
                        {
                            "dato": "2017-01-01",
                            "arsakType": "OPPTJENING",
                            "arsakDetails": [
                                "OPPTJENING_2012"
                            ],
                            "endringBelop": 83689.36381156495,
                            "pensjonsbeholdningBelop": 3047880.773674611,
                            "uttaksgrad": 0
                        },
                        {
                            "dato": "2017-05-01",
                            "arsakType": "REGULERING",
                            "arsakDetails": [
                                "REGULERING"
                            ],
                            "endringBelop": 34745.84081989061,
                            "pensjonsbeholdningBelop": 3082626.6144945016,
                            "uttaksgrad": 0
                        }
                    ]
                }
        },
        "numberOfYearsWithPensjonspoeng": 1
}
----