= Funksjonell oversikt

== Representasjon av opptjening for ulike brukergrupper
Hovedmålet for applikasjonen er å representere en liste av opptjeningsdata. Lista inneholder xref:Implementasjon:modell.adoc#opptjening[opptjening]-objekter, hvor hvert objekt inneholder all nødvendig informasjon for å gi et bilde av hva som påvirket brukerens opptjening til pensjon et bestemt år. Hvilke data som brukes for å representere brukerens opptjening et år avhenger av hvilken xref:Implementasjon:modell.adoc#userGroup[brukergruppe] den aktuelle brukeren tilhører. For brukere født etter 1962, som alle er på nytt regelverk, vil responsen kun populeres med pensjonsbeholdning. Pensjonspoeng blir ikke populert for disse brukerne. For brukere født fra og med 1954 og til og med 1962 vil både pensjonspoeng og pensjonsbeholdning populeres, fordi disse brukerne har både gammelt og nytt regelverk. For brukere født før 1954 er det kun pensjonspoeng som populeres, fordi disse brukerene kun er på gammelt regelverk.

For detaljer om regelverk for opptjening vises det til folketrygdloven:

- https://lovdata.no/dokument/NL/lov/1997-02-28-19/KAPITTEL_7-1#%C2%A719-16[Folketrygdloven kapittel 19] (Regelverk for dem født før 1954, delvis for dem født 1954–1963)
- https://lovdata.no/dokument/NL/lov/1997-02-28-19/KAPITTEL_7-2#%C2%A720-17[Folketrygdloven kapittel 20] (Regelverk for dem født etter 1962, delvis for dem født 1954–1962)

== Beregning av endring i pensjonsbeholdning
[#beregning_endring]
For brukergruppene som har opptjening i form av xref:Avhengigheter:avhengigheter-til-popp.adoc#beholdning[pensjonsbeholdning] (brukere født etter 1953) vil det være aktuelt å kunne vise hvordan denne pensjonsbeholdningen har forandret seg i løpet av et år. Økning i pensjonsbeholdning skjer som følge av inntekt man får fra arbeid eller ytelser det aktuelle året, samt som følge av en årlig regulering. Pensjonsbeholdningen kan også synke hvis bruker velger å ta ut pensjon. Hvor mye pensjonsbeholdningen reduseres avhenger da av uttaksgraden bruker velger for sin alderspensjon. Alle endringene som påvirker pensjonsbeholdningen i løpet av et år vil dermed bli lagt i lista _endringOpptjening_ på xref:Implementasjon:modell.adoc#opptjening[opptjening]-objektet. Hver enkelt endring representeres ved hjelp av objektet xref:Implementasjon:modell.adoc#endringOpptjening[EndringPensjonsopptjening]. Merk at endringer på pensjonsbeholdning kun blir populert fra 2010, da man mangler data for å beregne disse endringene for år før dette.

Det finnes en rekke forskjellige hendelser i løpet av et år som trigger en endring av pensjonsopptjening. Disse er beskrevet i tabellen xref:Implementasjon:modell.adoc#typeArsakCode[TypeArsakCode].

Hvordan beregnes de ulike endringene:

* Inngående: Endringer av typen INNGAENDE vil ha endringsbeløp alltid satt til 0, mens pensjonsbeholdningbeløp vil være satt til den beholdningen som bruker hadde siste dag forrige år.
* Opptjening: Endringer av typen OPPTJENING vil ha satt endringsbeløp lik det som står som beholdningInnskudd på beholdningen som gjelder på den første dagen i det aktuelle året. Endringsbeløpet reflekterer opptjening man har fått som følge av inntekten man hadde to år tilbake fra det aktuelle året.
Pensjonsbeholdningbeløpet settes til summen av endringen og pensjonsbeholdningbeløpet på inngående-endringen.
* Inngående 2010: Endringer markert INNGAENDE_2010 forekommer kun i året 2010. Disse er egentlig også å regne som opptjening, på samme måte som de som er markert OPPTJENING. Forskjellen er at det var først i 2010 at pensjonsreformen trådte i kraft og man begynte å benytte begrepet pensjonsbeholdning. Dermed ble all opptjening frem til 2008 regnet sammen for å danne en initiell pensjonsbeholdning i 2010. Dermed er opptjeningen i 2010 et resultat av opptjening fra alle år frem til 2008, og ikke bare et resultat av opptjening fra to år tilbake som vanlig opptjening er.
* Regulering: Endringer markert REGULERING er endringer i beholdning som skyldes den årlige lønnsvekstreguleringen som skjer hvert år. Endringsbeløpet på en slik endring tilsvarer reguleringsbeløpet på beholdningen som gjelder på første mai det aktuelle året. Pensjonsbeholdningbeløpet tilsvarer summen av pensjonsbeholdningsbeløpet på forrige endring i endringslista summert med reguleringsbeløpet fra beholdningen som gjelder første mai det aktuelle året.
* Uttak: Endringer markert UTTAK er endringer som skyldes at bruker har tatt ut alderspensjon. Når bruker tar ut alderspensjon reduseres pensjonsbeholdningen tilsvarende uttaksgraden. Endringsbeløpet reflekterer da dette ved at hvis brukeren har for eksempel uttaksgrad lik 100 %, så er endringsbeløpet lik -<total pensjonsbeholdning>. Merk at hvis bruker fremdeles har opptjening etter uttak av 100 % alderspensjon vil pensjonsbeholdningen øke tilsvarende opptjeningen. Hvis brukeren da har 100 % uttak blir da opptjeningen umiddelbart tatt ut, noe som resulterer i en endring markert med UTTAK som tilsvarer det negative av opptjeningen. Pensjonsbeholdningen som øker etter uttak av alderspensjon vil også bli regulert, og dermed øke. Denne økningen vil også reflekteres som en negativ endring markert UTTAK tilsvarende økningen man fikk i endringen markert REGULERING. Merk at dette tilfellet med umiddelbart uttak kun gjelder ved 100 % uttak, ikke ved gradert uttak hvor pensjonsbeholdningen bare vil fortsette å øke. Pensjonsbeholdningbeløpet på endringen tilsvarer pensjonsbeholdningen etter uttak. Ved 100 % uttak vil denne være 0, ved for eksempel 60 % uttak vil pensjonsbeholdningbeløpet tilsvare 40 % av den opprinnelige totale pensjonsbeholdningen.
* Utgående: Endringer markert UTGAENDE blir kun lagt til i lista hvis det forekommer en beholdning som har fom-dato på siste dag i det aktuelle året. Da settes kun pensjonsbeholdningsbeløpet lik denne beholdningen. Endringsbeløpet settes ikke.

Merk: Overnevnte liste beskriver overordnet funksjonelt de ulike endringstypene. Se koden for nøyaktige detaljer på hvordan de regnes ut.

== Merknader
Det kan i løpet av et år forekomme spesielle forhold som er relevante med tanke på opptjening. Disse opplyses om ved hjelp av ulike xref:Implementasjon:modell.adoc#merknadCode[merknadkoder] og settes på feltet merknader i xref:Implementasjon:modell.adoc#opptjening[opptjening]-objektet for det aktuelle året det spesielle forholdet inntraff.

Hver merknadkode vurderes for seg basert på gjeldende data det aktuelle året. Følgende vurderinger gjøres for hver merknad:

* AFP: Merknad om bruker har AFP det aktuelle året vurderes ved å se på AFP-historikken som er mottatt fra tjenesten xref:Avhengigheter:avhengigheter-til-pen.adoc#propen2602[PROPEN2602]. Hvis det aktuelle året er innenfor AFP-historikkens periode, legges koden AFP til i merknadlista.

* Uføregrad: Merknad om bruker er ufør det aktuelle året vurderes basert på uførehistorikken som er hentet fra tjenesten xref:Avhengigheter:avhengigheter-til-pen.adoc#propen2603[PROPEN2603]. Hvis det aktuelle året er innenfor uføreperioden legges koden UFOREGRAD til i merknadlisten. I tillegg settes feltet maksUforegrad på det aktuelle xref:Implementasjon:modell.adoc#opptjening[opptjening]-objektet.

* Reform: Merknaden REFORM legges til lista hvis det aktuelle året er 2010.

* Dagpenger og førstegangstjeneste: Hvis det finnes en beholdning slik at beholdning.dagpengebeløp.år er lik det aktuelle året og beholdning.dagpengebeløp.beløpordinær er større enn 0, så skal merknaden DAGPENGER legges til merknadlista for dette året. Tilsvarende hvis det finnes en beholdning slik at beholdning.forstegangstjenestebelop.år er lik det aktuelle året og beholdning.forstegangstjenestebeløp.beløp, så skal merknaden FORSTEGANGSTJENESTE legges til i merknadlista.

* Omsorgsopptjening: Hvis det finnes en beholdning hvor beholdning.omsorgsopptjeningBeløp.beløp er større enn 0 og beholdning.omsorgsopptjeningBelop.år er lik det aktuelle året, så skal merknaden OMSORGSOPPTJENING legges til i merknadlista for det aktuelle året. Hvis det for den samme beholdningen også er slik at xref:Avhengigheter:avhengigheter-til-popp.adoc#beholdning[beholdning].omsorgsopptjeningBelop.omsorgliste inneholder kodene OBU6 eller OBU7, så skal i tillegg merknaden OVERFORE_OMSORGSOPPTJENING legges til i merknadlista for det aktuelle året.

* Gradert og hel alderspensjon: Hvis det i lista som applikasjonen får fra xref:Avhengigheter:avhengigheter-til-pen.adoc#propen3001[PROPEN3001] forekommer en uttaksgrad som er gjeldende det aktuelle året, så skal det legges til merknad om uttak. Hvis den aktuelle uttaksgraden som gjelder på året er 100, skal merknaden HELT_UTTAK legges til i merknadlisten. Er uttaksgraden mindre enn 100 skal merknaden GRADERT_UTTAK legges til i merknadlisten i stedet.

* Ingen opptjening: Hvis det aktuelle xref:Implementasjon:modell.adoc#opptjening[opptjening]-objektet som skal populeres med merknader verken har fått satt pensjonsgivende inntekt, pensjonsbeholdning eller pensjonspoeng, samtidig som det ikke allerede eksisterer en merknad REFORM, så skal merknaden INGEN_OPPTJENING legges til i merknadlista for det aktuelle året.
