apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: pensjon-selvbetjening-opptjening-backend
  namespace: pensjonselvbetjening
  labels:
    team: pensjonselvbetjening
spec:
  image: {{ image }}
  port: 8080
  replicas:
    min: 1
    max: 1
  liveness:
    path: "/api/internal/isAlive"
    initialDelay: 30
    timeout: 1
    periodSeconds: 30
    failureThreshold: 5
  ingresses:
    - https://pensjon-selvbetjening-opptjening-backend.nais.preprod.local
  readiness:
    path: "/api/internal/isReady"
    initialDelay: 3
    timeout: 1
  env:
    - name: NO_NAV_SECURITY_JWT_ISSUER_SELVBETJENING_COOKIE_NAME
      value: selvbetjening-idtoken
    - name: HTTP_PROXY_PARAMETERNAME
      value: "http.proxy"
    - name: HTTP_PROXY
      value: http://webproxy-nais.nav.no:8088
    - name: UNLEASH_ENDPOINT_URL
      value: https://unleash.nais.io/api
    - name: APP_ENVIRONMENT
      value: q2
  envFrom:
    - configmap: loginservice-idporten
  prometheus:
    enabled: true
    path: /api/mgmt/prom
  vault:
    enabled: true
    paths:
      # Managed secrets
      - kvPath: /serviceuser/data/dev/srvpensjon
        mountPath: /secrets/serviceuser

