apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: pensjon-selvbetjening-opptjening-backend
  namespace: pensjonselvbetjening
  labels:
    team: pensjonselvbetjening
spec:
  image: {{ image }}
  port: 8080
  replicas:
    min: 1
    max: 1
  liveness:
    path: "/api/internal/isAlive"
    initialDelay: 30
    timeout: 1
    periodSeconds: 30
    failureThreshold: 5
  ingresses:
    - https://pensjon-selvbetjening-opptjening-backend.nais.preprod.local
  readiness:
    path: "/api/internal/isReady"
  env:
    - name: NO_NAV_SECURITY_JWT_ISSUER_SELVBETJENING_COOKIE_NAME
      value: selvbetjening-idtoken
    - name: HTTP_PROXY_PARAMETERNAME
      value: "http.proxy"
    - name: SKJERMING_ENDPOINT_URL
      value: https://skjermede-personer-pip.dev.adeo.no/
    - name: UNLEASH_ENDPOINT_URL
      value: https://unleash.nais.io/api
    - name: APP_ENVIRONMENT
      value: q2
    - name: AZURE_APP_REDIRECT_URI
      value: https://pensjon-selvbetjening-opptjening-frontend.dev.adeo.no/pensjon/opptjening/oauth2/internal/callback
  envFrom:
    - configmap: loginservice-idporten
  azure:
    application:
      enabled: true
      tenant: nav.no
      replyURLs:
        - https://pensjon-selvbetjening-opptjening-frontend.dev.adeo.no/pensjon/opptjening/oauth2/internal/callback
        - http://localhost:8080/oauth2/internal/callback
        - http://localhost:3000/oauth2/internal/callback
  webproxy: true
  prometheus:
    enabled: true
    path: /api/mgmt/prom
  vault:
    enabled: true
    paths:
      # Managed secrets
      - kvPath: /serviceuser/data/dev/srvpensjon
        mountPath: /secrets/serviceuser

