apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: pensjon-selvbetjening-opptjening-backend
  namespace: default
  labels:
    team: pensjonselvbetjening
spec:
  image: {{ image }}
  port: 8080
  replicas:
    min: 2
    max: 2
  liveness:
    path: "/api/internal/isAlive"
    initialDelay: 30
    timeout: 1
    periodSeconds: 30
    failureThreshold: 5
  ingresses:
    - https://pensjon-selvbetjening-opptjening-backend.adeo.no
    - https://pensjon-selvbetjening-opptjening-backend.nais.adeo.no
  readiness:
    path: "/api/internal/isReady"
    initialDelay: 3
    timeout: 1
  env:
    - name: NO_NAV_SECURITY_JWT_ISSUER_SELVBETJENING_COOKIE_NAME
      value: selvbetjening-idtoken
    - name: HTTP_PROXY_PARAMETERNAME
      value: "http.proxy"
    - name: HTTP_PROXY
      value: http://webproxy-nais.nav.no:8088
    - name: SERVICEUSERTOKEN_ENDPOINT_URL
      value: https://security-token-service.nais.adeo.no/rest/v1/sts/token
    - name: PEN_ENDPOINT_URL
      value: https://pensjon-pen.nais.adeo.no/pen/api/
    - name: POPP_ENDPOINT_URL
      value: https://pensjon-popp.nais.adeo.no/popp/api
    - name: PDL_ENDPOINT_URL
      value: https://pdl-api.nais.adeo.no/graphql
    - name: UNLEASH_ENDPOINT_URL
      value: https://unleash.nais.io/api
    - name: APP_ENVIRONMENT
      value: p
  envFrom:
    - configmap: loginservice-idporten
  prometheus:
    enabled: true
    path: /api/mgmt/prom
  vault:
    enabled: true
    paths:
      - kvPath: /serviceuser/data/prod/srvpensjon
        mountPath: /secrets/serviceuser
