name: "Deploy to dev-gcp"

on: workflow_dispatch

jobs:
  deploy-to-dev-gcp:
    name: Deploy to dev-gcp
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Setup cache
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Build
        run: mvn -B package --file pom.xml
      - name: Docker build push
        uses: nais/docker-build-push@v0
        id: docker-build-push
        with:
          team: pensjonselvbetjening
          dockerfile: .docker/Dockerfile
      - name: Deploy to gcp
        uses: nais/deploy/actions/deploy@v2
        env:
          IMAGE: ${{ steps.docker-build-push.outputs.image }}
          CLUSTER: dev-gcp
          RESOURCE: .nais/dev-gcp.yml
